/**
 * Online shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DeliveryInfo } from './deliveryInfo';
import { PaymentInfo } from './paymentInfo';
import { SaleInfo } from './saleInfo';


export interface OrderInfo {
    id?: string;
    status?: string;
    deliveryInfo?: DeliveryInfo;
    paymentInfo?: PaymentInfo;
    saleInfo?: SaleInfo;
}
